name: iraqi_license_plate_example
description: Example app for the iraqi_license_plate package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  iraqi_license_plate:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
